### ISSUE TITLE
numerous technical issues regarding the rendering of text

### ISSUE THREAD

**Issue by rveerepalli** [cyckl/cyckl.github.io#2]
When I visited the blog, I noticed that the text was being rendered incorrectly on my laptop. I am not sure where exactly this problem stems from, but it made the site almost unusable.
To provide some background, here are some details regarding my system, though I'm not sure how relevant they are:
- Laptop: ThinkPad T420
- OS: OpenBSD
- Browser: Firefox

I do not know whether this issue is something on my end or something related to the website itself. The specific issue had to do with some of the text on the navigation bar. Although the text is supposed to render as "Cauldron", for whatever reason, the text is rendered as "Calderon," which we know is fundamentally wrong, according to Ian's laws of the universe. Please fix this issue as soon as possible.

**Comment by cyckl** [comment]
This appears to be a very grave problem! I'll contact the relevant authorities to get this handled.
