### ISSUE TITLE
css issues

### ISSUE THREAD

**Issue by IanLoam126** [cyckl/cyckl.github.io#3]
>_ 

> 

> # I was looking at the blog and I came to notice some faulty css on my computer. I don't believe it  was intended for, but the colors are excessively bright for most viewers to see. Just as a precaution it may be necessary to include some type of seizure warning

## before entering your website, or changing the background to a less offensive color such as #39ff14.

1.                   

# While I am still here, I might as well also include that the usage of the term "cyckl" may be 

- 

- 

- 

 excessively offensive for any average or non extremist person browsing your page to view. As we all know the name "cyckl" is pronounced like the word "tickle", which may have some excessively inappropriate connotations. I would recommend that every reference 

 of the word you would put in parenthesis that it is 
# "not tickle". 
Also, you spelled "cyckl" wrong, the correct way to do it is "crick". Please fix these issues as soon as you can.

**Comment by rveerepalli** [comment]
I agree. Also, the website is not at all accessible for blind people. You may want to consider fixing this including a braille option for your website.

**Comment by IanLoam126** [comment]
actually i may be wron g abuot the spelling of "cyckl". since his email is bi.cyckl(at)gmail.com it would make more sense that "cyckl" is spelled "sexual" so that the email could be an advertisement for any onlookers that may be trying to find this danny common

**Comment by rveerepalli** [comment]
who is danny common?

**Comment by IanLoam126** [comment]
a

**Comment by IanLoam126** [comment]
you are stop it

**Comment by rveerepalli** [comment]
<sub>red</sub>

**Comment by IanLoam126** [comment]
i am having chicken for dinner. no no no no yes

**Comment by IanLoam126** [comment]
okay

**Comment by IanLoam126** [comment]
Okay

**Comment by IanLoam126** [comment]
okaY

**Comment by rveerepalli** [comment]
> go away

**Comment by IanLoam126** [comment]
![Capture2](https://user-images.githubusercontent.com/31806605/80852521-19cbab00-8bde-11ea-9415-34d46944a741.JPG)

**Comment by IanLoam126** [comment]
[https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Human-Hands-Front-Back.jpg/240px-Human-Hands-Front-Back.jpg](url)
